apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.15.1
          ports:
            - containerPort: 5601
          env:
            - name: KBN_PATH_CONF
              value: /usr/share/kibana/config
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - |
                    rm -f /usr/share/kibana/config/kibana.yml
                    echo '
                    server.host: "0.0.0.0"
                    server.shutdownTimeout: "5s"
                    elasticsearch.hosts: ["https://34.59.196.141:9200"]
                    elasticsearch.username: "kibana_system"
                    elasticsearch.password: "XHmh9AoBoVnFzN25zphO"
                    monitoring.ui.container.elasticsearch.enabled: true
                    elasticsearch.ssl.verificationMode: none
                    ' > /usr/share/kibana/config/kibana.yml
      volumes:
        - name: kibana-config
